accounts/urls.py
from django.urls import path

import django.contrib.auth.views as auth_views

from . import views

app_name='accounts'

urlpatterns = [
	path('',views.HomeView,name='index'),
	path('all_users/',views.users_list,name='all_users'),
	path('request/<int:id>',views.send_friend_request,name='send_request'),
	path('sentRequests/',views.show_send_requests,name='show_sent'),
	path('cancelRequests/<int:id>',views.cancel_friend_request,name='cancel_sent'),
	path('recieveRequests/',views.show_recieve_requests,name='show_recieve'),
	path('acceptRequest/<int:id>',views.accept_friend_request,name='accept_request'),
	path('profile/<int:id>',views.user_profile,name='user_profile'),
	path('unfriend/<int:id>',views.unfriend_user,name='unfriend_user'),

	path('login/',auth_views.login,name='login'),
	path('logout/',auth_views.logout,name='logout'),

]

chat/urls.py
from django.urls import path
from . import views

app_name='chat'

urlpatterns = [
	path('<int:id>',views.showMessage,name='show_message'),
	path('<int:id>/sendMessage',views.sendMessage,name='send_message'),
	path('<int:id>/getMessage',views.getMessage,name='get_message'),
	path('showMessage/',views.show_all_Message,name='show_all_messages'),
	path('getAllMessage/',views.get_all_Message,name='get_all_messages'),
]

chatApp2/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('message/',include('chat.urls')),
    path('',include('accounts.urls')),
]

accounts/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User
# Create your models here.
from django.db.models.signals import post_save

class Profile(models.Model):
	user = models.OneToOneField(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
	slug=models.SlugField()
	friends=models.ManyToManyField("Profile",blank=True)

	def __str__(self):
		return self.user.username

def post_save_usermodel_profile(sender,instance,created,*args,**kwargs):
	if created:
		try:
			Profile.objects.create(user=instance)
		except:
			pass

post_save.connect(post_save_usermodel_profile,sender=settings.AUTH_USER_MODEL)

class friendRequest(models.Model):
	to_user=models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE,related_name='to_user')
	from_user=models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE,related_name='from_user')
	timestamp=models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return self.to_user.username + " - " + self.from_user.username

chat/models.py
from django.db import models
from django.conf import settings

from django.contrib.auth.models import User

# Create your models here.

class chat(models.Model):
	message=models.CharField(max_length=500)
	message_to=models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE,related_name='message_to')
	message_from=models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE,related_name='message_from')
	send_date=models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return  str(self.message_from) + " - " +str(self.message_to)  + " : " + str(self.message) 

chat/forms.py
from django import forms
from .models import chat


class ChatForm(forms.ModelForm):
	class Meta:
		model=chat
		fields=['message']

accounts/views.py
from django.shortcuts import render,get_object_or_404
from django.conf import settings

from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required

from django.http import HttpResponseRedirect
from django.db.models import Q

# Create your views here.

from .models import Profile,friendRequest


@login_required
def HomeView(request):
	user_profile=Profile.objects.get(user=request.user)
	connected=user_profile.friends.all()
	context={
		'friends':connected
	}
	return render(request,'accounts/home.html',context)

def users_list(request):
	user_profile=Profile.objects.get(user=request.user)
	users=Profile.objects.filter().exclude(profile=user_profile).exclude(user=request.user)
	context={
		'all_users':users,
	}
	return render(request,'accounts/all_users.html',context)

def show_send_requests(request):
	requests=friendRequest.objects.filter(from_user=request.user)
	context={
		'requests':requests,
	}
	return render(request,'accounts/sentRequest.html',context)

def show_recieve_requests(request):
	requests=friendRequest.objects.filter(to_user=request.user)
	context={
		'requests':requests,
	}
	return render(request,'accounts/recieveRequest.html',context)

def send_friend_request(request,id):
	to_user=get_object_or_404(User,id=id)
	from_user=request.user
	frequest,created=friendRequest.objects.get_or_create(
		from_user=from_user,
		to_user=to_user
		)
	return HttpResponseRedirect('/')

def cancel_friend_request(request,id):
	to_user=get_object_or_404(User,id=id)
	frequest=friendRequest.objects.get(
		to_user=to_user,
		from_user=request.user
		)
	frequest.delete()
	return HttpResponseRedirect('/')

def accept_friend_request(request,id):
	user1=get_object_or_404(User,id=id)
	user2=request.user
	frequest=friendRequest.objects.filter(to_user=user2,from_user=user1).first()
	user1_profile=Profile.objects.get(user=user1)
	user2_profile=Profile.objects.get(user=user2)
	user1_profile.friends.add(user2_profile)
	user2_profile.friends.add(user1_profile)
	frequest.delete()
	return HttpResponseRedirect('/')


def unfriend_user(request,id):
	selected_user=get_object_or_404(User,id=id)
	user1_profile=Profile.objects.get(user=request.user)
	user2_profile=Profile.objects.get(user=selected_user)
	user1_profile.friends.remove(user2_profile)
	user2_profile.friends.remove(user1_profile)
	return HttpResponseRedirect('/')

def user_profile(request,id):
	selected_user=get_object_or_404(User,id=id)
	context={
		'selected_user':selected_user,
	}
	return render(request,'accounts/profile.html',context)

chat/views.py
from django.shortcuts import render,get_object_or_404

from django.contrib.auth.models import User
from django.http import JsonResponse
from django.db.models import Q

from .forms import ChatForm

from .models import chat
from accounts.models import friendRequest,Profile

# Create your views here.


def showMessage(request,id):
	messages=''
	to_user=get_object_or_404(User,id=id)
	form=ChatForm()
	if(to_user==request.user):
		message="Chatting with yourself huh !!"
	else:
		to_user_profile=get_object_or_404(Profile,user=to_user)
		request_user_profile=Profile.objects.get(user=request.user)
		if(request_user_profile.friends.filter(user=to_user).first()):
			status=True
			message="Connected to " + to_user.username
			messages = chat.objects.filter(message_to=request.user,message_from=to_user) | chat.objects.filter(message_to=to_user,message_from=request.user)
			messages.order_by('pk')
		else:
			status=False
			message="Connection terminated , You are not friends with " + to_user.username
	context={
		'messages':messages,
		'reciever_id':id,
		'status':status,
		'message': message,
		'form':form,
	}
	return render(request,'chat/message.html',context)

def sendMessage(request,id):
	message=request.GET.get('message',None)
	reciever=User.objects.get(id=id)
	if message:
		message=chat(message_from=request.user,message_to=reciever,message=message);
		message.save()
		data={
			'message':'Message Has been sent',
		}
	else:
		data={
			'message':'Error in sending message',
		}
	return JsonResponse(data)

def getMessage(request,id):
	user2=get_object_or_404(User,id=id);
	messages = chat.objects.filter(message_to=request.user,message_from=user2) | chat.objects.filter(message_to=user2,message_from=request.user)
	messages.order_by('pk')
	data_set=[]
	for msg in messages:
		message=msg.message
		message_to=msg.message_to.username
		message_from=msg.message_from.username
		if message_to==request.user.username:
			status=1
		else:
			status=0
		data_pack={
			'message':message,
			'message_to':message_to,
			'message_from':message_from,
			'status':status
		}
		data_set.append(data_pack)
	data={
		'messages':data_set,
	}
	return JsonResponse(data)

def show_all_Message(request):
	return render(request,'chat/showMessage.html',{})

def get_all_Message(request):
	data_set=[]
	convo_users=User.objects.filter(
			Q(message_to__message_from=request.user)|
			Q(message_from__message_to=request.user)
		).distinct()
	for convo in convo_users:
		msg=chat.objects.filter(
			Q(message_to=request.user,message_from=convo) |
			Q(message_to=convo, message_from=request.user)).last()
		data_pack={
			'user':convo.username,
			'msg':msg.message,
		}
		data_set.append(data_pack)
	data={
		'all_messages':data_set,
	}
	return JsonResponse(data)

accounts/templates/accounts/all_users.html
{% extends 'accounts/base.html' %}

{% block title %}
	All - Users
{% endblock %}

{% block content %}
	
All Users

		<br><br>
{% if all_users %}

		{% for user in all_users %}
			&nbsp;&nbsp;&nbsp;&nbsp;{{user}} <a href="{% url 'accounts:send_request' user.id %}">Send Request</a><br>
		{% endfor %}

	{% else %}

		No users currently available

	{% endif %}

{% endblock %}

accounts/templates/accounts/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
	<title>{% block title%}
			{%endblock%}
	</title>

	<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="{% static 'accounts/css/materialize.min.css' %}">
 <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
</head>
<body>
 <nav class="nav-extended cyan darken-1">
    <div class="nav-wrapper">
      <a href="#" class="brand-logo center">Chatty</a>
      <a href="#" data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons">menu</i></a>
      
    </div>
    <div class="nav-content">
        <div class="container">
      <ul class="tabs tabs-transparent hide-on-med-and-down">
        <li class="tab"><a class="active" href="{% url 'accounts:index'%}">Home</a></li>
        <li class="tab"><a href="{% url 'chat:show_all_messages' %}">Messages</a></li>
        <li class="tab"><a href="#">Profile</a></li>
        <li class="tab"><a href="{% url 'accounts:all_users'%}">All users</a></li>
        <li class="tab"><a href="{% url 'accounts:show_sent' %}">Sent Requests</a></li>
        <li class="tab"><a href="{% url 'accounts:show_recieve'%}">Recieved Requests</a></li>
      </ul>
  </div>
    </div>
  </nav>

    <ul class="sidenav" id="mobile-demo">
        <div class="user-view">
            <div class="background">
                <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQVGDJxR7DDpbdvIy3Yn9GHGGi8w0Ceux_LQnAQcSnLUV5cV_1o">
            </div>
            <a href="#"><img src="https://img.icons8.com/color/1600/circled-user-male-skin-type-1-2.png" class="circle"></a>
            <a href="#"><span class="white-text name">Binish Manandhar</span></a>
            <a href="#"><span class="white-text email">binish784@hotmail.com</span></a>
        </div>
        <li class="tab"><a class="active" href="{% url 'accounts:index'%}">Home</a></li>
        <li class="tab"><a href="#">Messages</a></li>
        <li class="tab"><a href="#">Profile</a></li>
        <li class="tab"><a href="{% url 'accounts:all_users'%}">All users</a></li>
        <li class="tab"><a href="{% url 'accounts:show_sent' %}">Sent Requests</a></li>
        <li class="tab"><a href="{% url 'accounts:show_recieve'%}">Recieved Requests</a></li>
    </ul>
<br><br>

<div class="container">
    {% block content%}

    {% endblock%}
</div>

    <!-- Compiled and minified JavaScript -->

<!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/smoothness/jquery-ui.css">
	<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script></script>
    <script type="text/javascript" src="{% static 'accounts/js/materialize.min.js' %}"></script>
	
<script type="text/javascript">
      $(document).ready(function(){
        $('.sidenav').sidenav();
      });   
</script>

{% block script%}

{% endblock%}

</body>
</html>

accounts/templates/accounts/home.html
{% extends 'accounts/base.html' %}

{% block title %}
	Home-Page
{% endblock %}

{% block content %}
	<br><br>Welcome-to-my-homepage &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
	<a href="{% url 'accounts:logout' %}">Logout</a>
	<br><br>

	
<br><br>
	Connected to : <br><br>

	{% if friends %}
		{% for friend in friends %}
			<a href="{% url 'accounts:user_profile' friend.id %}">{{friend}}</a> &nbsp;&nbsp;&nbsp;&nbsp;<a href="{% url 'chat:show_message' friend.id%}"> Send Message</a><br>
		{% endfor %}
	{% else %}
		You are not connected to anyone
	{% endif %}

{% endblock %}

accounts/templates/accounts/profile.html
{% extends 'accounts/base.html' %}

{% block title %}
	User-Profile
{% endblock %}


{% block content %}

{{selected_user.username}} &nbsp;&nbsp;&nbsp;&nbsp;<a href="{% url 'accounts:unfriend_user' selected_user.id%}">unFriend</a>

{% endblock %}

accounts/templates/accounts/recieveRequest.html
{% extends 'accounts/base.html' %}

{% block title %}
	Recieved Requests
{% endblock %}

{% block content %}

	Recieved Requests:<br><Br>
	{% if requests %}
		{% for request in requests %}
			{{request.from_user}}&nbsp;&nbsp;&nbsp;<a href="{% url 'accounts:accept_request' request.from_user.id %}">Accept </a>&nbsp;&nbsp;<a href="">Cancel </a>
		{% endfor %}
	{% else %}
		You have no friend requests.
	{% endif%}


{% endblock %}

accounts/templates/accounts/sentRequest.html
{% extends 'accounts/base.html' %}

{% block title %}
	Requests Sent
{% endblock %}

{% block content %}
	The requests you sent will appear here
<br><br>
	{% if requests %}
		{% for request in requests %}
			{{request.to_user}}&nbsp;&nbsp;&nbsp;<a href="{% url 'accounts:cancel_sent' request.to_user.id%}">Cancel Request</a><br>
		{% endfor %}
	{% else %}
		You have no requests currently
	{% endif %}

{% endblock %}

chat/templates/chat/message.html
{% extends 'accounts/base.html' %}

{% load static %}

{% block title %}
	Send Message
{% endblock %}

{% block content %}


	{% if message %}
		{{message}}

	{% endif %}
<a href="{% url 'accounts:index' %}">Go Home</a>

{% if status %}
<form method="GET" action="{% url 'chat:send_message' reciever_id %}" id='msgForm'>

{% csrf_token %}	
	{{form}}
	<input type="Submit" value="Send">
</form>
<br>

<div id='msgBlock' get_msg_action="{% url 'chat:get_message' reciever_id %}">

{% if messages %}
	{% for msg in messages %}

		{% if msg.message_to == request.user%}

			<p style="color: red">{{msg.message}}</p>

		{% else %}

			<p style="color:green">{{msg.message}}</p>

		{% endif%}

	{% endfor %}
{% else %}
	Start an conversation now
{% endif %}

</div>
	
{% endif %}

{% endblock %}

{% block script %}
 	
	<script type="text/javascript" src="{% static 'chat/safeAjax.js' %}"></script>

	<script type="text/javascript">

		form=$("#msgForm");
		msgBlock=$("#msgBlock");

		form.submit(function(e){
			e.preventDefault();
			$formData=form.serialize();
			$.ajax({
				method:form.attr('method'),
				url:form.attr('action'),
				data:$formData,
				dataType:'json',
				contentType:'application/json',
				success:function(data){

					$("#id_message").val("");
					console.log(data);
				}
			})			
		})

			setInterval(function(){
				$.ajax({
					method:'GET',
					url:msgBlock.attr('get_msg_action'),
					dataType:'json',
					contentType:'application/json',
					success:function(data){
						msgBlock.html("")
						for(var key in data.messages){
							if(data.messages[key].status){
								msgBlock.append("<p style='color:red'>"+ data.messages[key].message+"</p>");
							}else{
								msgBlock.append("<p style='color:green'>"+ data.messages[key].message+"</p>");
							}
						}
					}
				})
			},500)


	</script>

{% endblock %}

chat/templates/chat/showMessage.html
{% extends 'accounts/base.html' %}

{% block title %}
	All messages
{% endblock %}

{% block content %}
	
	All conversations are shown here
<br><br>
<div id="Convo_block" convo_get_action="{% url 'chat:get_all_messages' %}">
	
</div>

{% endblock %}

{% block script %}

<script type="text/javascript">
	

convoBlock=$("#Convo_block");

setInterval(function(){
	


$.ajax({
	method:'GET',
	dataType:'json',
	contentType:'application/json',
	url:convoBlock.attr('convo_get_action'),
	success:function(data){
		convoBlock.html("");
		for(var key in data.all_messages){
			convoBlock.append(data.all_messages[key].user + " : ");
			convoBlock.append(data.all_messages[key].msg +"<br><br>");

		}

	}
});

},500);	


</script>

{% endblock %}